name: FIDELYCS CI/CD PIPELINE

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: | 
        touch .env
        echo "${{secrets.PROD_ENV_FILE}}" | tr -d '\r' > .env
        # echo "${{secrets.PROD_ENV_FILE}}" >> .env
    - run: npm run build

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Deploy with PM2
      run: pm2 start dist/main.js --name "backendAllioV0"
